### ISSUE TITLE
gitignore Cargo.lock so it doesn't need to be updated

### ISSUE THREAD

**Issue by lesleyrs** [jjant/runty8-game-template#1]
Wouldn't it be better to not include the lock file in this repo so people who create a template get the latest changes? Or is there a reason why you wouldn't want to run `cargo update` after cloning?

Edit: Never mind this doesn't seem to work the way I want. My intention was to match whatever crates Runty8 `master` branch was using but idk if that is possible. Runty8 also has no lock file committed.

**Comment by jjant** [comment]
Yes, I think this should be fine. 

> My intention was to match whatever crates Runty8 master branch was using but idk if that is possible.

You'd still get semver-compatible versions of the other/transitive dependencies so those shouldn't break your build.

> Runty8 also has no lock file committed.

That's on purpose, [libraries are not supposed to commit lock files](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html#cargotoml-vs-cargolock).

**Comment by lesleyrs** [comment]
Great!
