### ISSUE TITLE
Why is game width and height set to 7?

### ISSUE THREAD

**Issue by lesleyrs** [jjant/runty8-game-template#2]
https://github.com/jjant/runty8-game-template/blob/5279cfbe985d8010a8c29081cbb570889a6159da/src/main.rs#L44-L47

**Comment by jjant** [comment]
It's just the size of the box: 
https://github.com/jjant/runty8-game-template/blob/5279cfbe985d8010a8c29081cbb570889a6159da/src/main.rs#L33-L39

It's an odd number so that the square can be drawn centered on your position (if it were even it'd be one pixel off either to the left or right).

**Comment by lesleyrs** [comment]
Oh lmao... I deleted that and didn't realize it was using those consts for the square, that was dumb.

I'm using them for getting the actual window width and height instead by setting it to 127.
